export const INVENTORYCATEGORY_LIST_REQUEST = "INVENTORYCATEGORY_LIST_REQUEST";
export const INVENTORYCATEGORY_LIST_SUCCESS = "INVENTORYCATEGORY_LIST_SUCCESS";
export const INVENTORYCATEGORY_LIST_FAIL = "INVENTORYCATEGORY_LIST_FAIL";

export const INVENTORYCATEGORY_DETAILS_REQUEST =
  "INVENTORYCATEGORY_DETAILS_REQUEST";
export const INVENTORYCATEGORY_DETAILS_SUCCESS =
  "INVENTORYCATEGORY_DETAILS_SUCCESS";
export const INVENTORYCATEGORY_DETAILS_FAIL = "INVENTORYCATEGORY_DETAILS_FAIL";
