export const INVENTORYLEVEL_LIST_REQUEST = 'INVENTORYLEVEL_LIST_REQUEST'
export const INVENTORYLEVEL_LIST_SUCCESS = 'INVENTORYLEVEL_LIST_SUCCESS'
export const INVENTORYLEVEL_LIST_FAIL = 'INVENTORYLEVEL_LIST_FAIL'

export const INVENTORYLEVEL_SALARY_REQUEST = 'INVENTORYLEVEL_SALARY_REQUEST'
export const INVENTORYLEVEL_SALARY_SUCCESS = 'INVENTORYLEVEL_SALARY_SUCCESS'
export const INVENTORYLEVEL_SALARY_FAIL = 'INVENTORYLEVEL_SALARY_FAIL'

export const INVENTORYLEVEL_GROUPED_REQUEST = 'INVENTORYLEVEL_GROUPED_REQUEST'
export const INVENTORYLEVEL_GROUPED_SUCCESS = 'INVENTORYLEVEL_GROUPED_SUCCESS'
export const INVENTORYLEVEL_GROUPED_FAIL = 'INVENTORYLEVEL_GROUPED_FAIL'

export const INVENTORYLEVEL_CREATE_REQUEST = 'INVENTORYLEVEL_CREATE_REQUEST'
export const INVENTORYLEVEL_CREATE_SUCCESS = 'INVENTORYLEVEL_CREATE_SUCCESS'
export const INVENTORYLEVEL_CREATE_FAIL = 'INVENTORYLEVEL_CREATE_FAIL'
export const INVENTORYLEVEL_CREATE_RESET = 'INVENTORYLEVEL_CREATE_RESET'

export const INVENTORYLEVEL_DELETE_REQUEST = 'INVENTORYLEVEL_DELETE_REQUEST'
export const INVENTORYLEVEL_DELETE_SUCCESS = 'INVENTORYLEVEL_DELETE_SUCCESS'
export const INVENTORYLEVEL_DELETE_FAIL = 'INVENTORYLEVEL_DELETE_FAIL'

export const INVENTORYLEVEL_UPDATE_REQUEST = 'INVENTORYLEVEL_UPDATE_REQUEST'
export const INVENTORYLEVEL_UPDATE_SUCCESS = 'INVENTORYLEVEL_UPDATE_SUCCESS'
export const INVENTORYLEVEL_UPDATE_FAIL = 'INVENTORYLEVEL_UPDATE_FAIL'
export const INVENTORYLEVEL_UPDATE_RESET = 'INVENTORYLEVEL_UPDATE_RESET'

export const INVENTORYLEVEL_DETAILS_REQUEST = 'INVENTORYLEVEL_DETAILS_REQUEST'
export const INVENTORYLEVEL_DETAILS_SUCCESS = 'INVENTORYLEVEL_DETAILS_SUCCESS'
export const INVENTORYLEVEL_DETAILS_FAIL = 'INVENTORYLEVEL_DETAILS_FAIL'