export const INVENTORY_LIST_REQUEST = 'INVENTORY_LIST_REQUEST'
export const INVENTORY_LIST_SUCCESS = 'INVENTORY_LIST_SUCCESS'
export const INVENTORY_LIST_FAIL = 'INVENTORY_LIST_FAIL'

export const INVENTORY_SALARY_REQUEST = 'INVENTORY_SALARY_REQUEST'
export const INVENTORY_SALARY_SUCCESS = 'INVENTORY_SALARY_SUCCESS'
export const INVENTORY_SALARY_FAIL = 'INVENTORY_SALARY_FAIL'

export const INVENTORY_UNPAID_REQUEST = 'INVENTORY_UNPAID_REQUEST'
export const INVENTORY_UNPAID_SUCCESS = 'INVENTORY_UNPAID_SUCCESS'
export const INVENTORY_UNPAID_FAIL = 'INVENTORY_UNPAID_FAIL'

export const INVENTORY_COST_REQUEST = 'INVENTORY_COST_REQUEST'
export const INVENTORY_COST_SUCCESS = 'INVENTORY_COST_SUCCESS'
export const INVENTORY_COST_FAIL = 'INVENTORY_COST_FAIL'

export const INVENTORY_CREATE_REQUEST = 'INVENTORY_CREATE_REQUEST'
export const INVENTORY_CREATE_SUCCESS = 'INVENTORY_CREATE_SUCCESS'
export const INVENTORY_CREATE_FAIL = 'INVENTORY_CREATE_FAIL'
export const INVENTORY_CREATE_RESET = 'INVENTORY_CREATE_RESET'

export const INVENTORY_DELETE_REQUEST = 'INVENTORY_DELETE_REQUEST'
export const INVENTORY_DELETE_SUCCESS = 'INVENTORY_DELETE_SUCCESS'
export const INVENTORY_DELETE_FAIL = 'INVENTORY_DELETE_FAIL'

export const INVENTORY_UPDATE_REQUEST = 'INVENTORY_UPDATE_REQUEST'
export const INVENTORY_UPDATE_SUCCESS = 'INVENTORY_UPDATE_SUCCESS'
export const INVENTORY_UPDATE_FAIL = 'INVENTORY_UPDATE_FAIL'
export const INVENTORY_UPDATE_RESET = 'INVENTORY_UPDATE_RESET'

export const INVENTORY_DETAILS_REQUEST = 'INVENTORY_DETAILS_REQUEST'
export const INVENTORY_DETAILS_SUCCESS = 'INVENTORY_DETAILS_SUCCESS'
export const INVENTORY_DETAILS_FAIL = 'INVENTORY_DETAILS_FAIL'

export const INVENTORY_GROUP_REQUEST = 'INVENTORY_GROUP_REQUEST'
export const INVENTORY_GROUP_SUCCESS = 'INVENTORY_GROUP_SUCCESS'
export const INVENTORY_GROUP_FAIL = 'INVENTORY_GROUP_FAIL'

export const INVENTORY_DATES_REQUEST = 'INVENTORY_DATES_REQUEST'
export const INVENTORY_DATES_SUCCESS = 'INVENTORY_DATES_SUCCESS'
export const INVENTORY_DATES_FAIL = 'INVENTORY_DATES_FAIL'