export const RECEIPT_LIST_REQUEST = "RECEIPT_LIST_REQUEST";
export const RECEIPT_LIST_SUCCESS = "RECEIPT_LIST_SUCCESS";
export const RECEIPT_LIST_FAIL = "RECEIPT_LIST_FAIL";

export const RECEIPT_UNPAID_REQUEST = "RECEIPT_UNPAID_REQUEST";
export const RECEIPT_UNPAID_SUCCESS = "RECEIPT_UNPAID_SUCCESS";
export const RECEIPT_UNPAID_FAIL = "RECEIPT_UNPAID_FAIL";

export const RECEIPT_PAID_REQUEST = "RECEIPT_PAID_REQUEST";
export const RECEIPT_PAID_SUCCESS = "RECEIPT_PAID_SUCCESS";
export const RECEIPT_PAID_FAIL = "RECEIPT_PAID_FAIL";

export const RECEIPT_REMOVE_REQUEST = "RECEIPT_REMOVE_REQUEST";
export const RECEIPT_REMOVE_SUCCESS = "RECEIPT_REMOVE_SUCCESS";
export const RECEIPT_REMOVE_FAIL = "RECEIPT_REMOVE_FAIL";

export const RECEIPT_DETAILS_REQUEST = "RECEIPT_DETAILS_REQUEST";
export const RECEIPT_DETAILS_SUCCESS = "RECEIPT_DETAILS_SUCCESS";
export const RECEIPT_DETAILS_FAIL = "RECEIPT_DETAILS_FAIL";
export const RECEIPT_DETAILS_RESET = "RECEIPT_DETAILS_RESET";
